Feature/inscription
lescadev/loupelou pull request #16
Opened 2019-06-04 12:58 UTC by VirginiePHILIPPE

formulaires inscription particulier et professionnel, avec hashage du mot de passe

2019-06-04 13:37 UTC, Anthony8729 approved these changes

2019-06-04 14:17 UTC, Mihidari approved these changes

2019-06-04 14:35 UTC, NicolasROULON approved these changes

2019-06-04 14:52 UTC, NicolasROULON commented
A corriger : 
- obligation d'un siret lors d'une inscription en tant que comptoir.
- obligation d'un site internet lors d'une inscription en tant que comptoir ou professionnel.

2019-06-04 14:59 UTC, lescadev requested changes

2019-06-04 14:59 UTC, lescadev commented on templates/inscription/index.html.twig
> +<style>
This is strictly forbidden !
No CSS in HTML templates.

2019-06-04 14:59 UTC, lescadev commented on templates/particuliers/particuliers.html.twig
> +            <button type="submit"> Imprimez le formulaire</button>
Two submit buttons for one form ? How bizarre…
The second should be a simple button with a JS onclick event

2019-06-05 09:32 UTC, Anthony8729 approved these changes

2019-06-05 10:12 UTC, lescadev commented on templates/particuliers/particuliers.html.twig
> +<p> * Champs Obligatoire </p>
s

2019-06-05 10:12 UTC, lescadev commented on templates/professionnels/professionnels.html.twig
> +<p> * Champs Obligatoire </p>
s

2019-06-05 10:15 UTC, lescadev commented on src/Controller/ParticuliersController.php
> +            $this->addFlash('success', 'Inscription réussi!');
e

2019-06-05 10:25 UTC, lescadev approved these changes

2019-06-05 10:27 UTC, Toohk approved these changes

2019-06-05 10:28 UTC, merged