Mise en place du Layout front + routes
lescadev/loupelou pull request #3
Opened 2019-05-21 08:12 UTC by MathieuCornut

2019-05-21 08:33 UTC, lescadev requested changes
**CSS :**
- Please insert normalize CSS
- Rename file to style.css
- Correct indentation and code style
- REMOVE ALL FLOAT PROPERTIES !!!

**BASE LAYOUT :**
- Insert your CSS AFTER the stylesheets block
- The routes are not correctly used in navigation

**PAGE LAYOUT :**
- The title block is not correctly overridden
- One template for same pages types would be better

**CONTROLLER :**
- Rename to HomeController
- The routes are not correctly defined

2019-05-21 12:50 UTC, VirginiePHILIPPE approved these changes

2019-05-21 14:20 UTC, lescadev requested changes

2019-05-21 14:20 UTC, lescadev commented on src/Controller/HomeController.php
> +    public function home()
Please rename this action from "home" to "index"

2019-05-21 14:20 UTC, lescadev commented on src/Controller/HomeController.php
> +        return $this->render('/home.html.twig');
Sure that the "/" is necessary ?

2019-05-21 14:20 UTC, lescadev commented on templates/base.html.twig
> +                <a href="/header/login"><img src="/iconuser.svg" alt="connection/inscription" class="iconuser"></a>
This is not a route call

2019-05-21 14:20 UTC, lescadev commented on templates/base.html.twig
>                  <a href="/home"><img src="/logoloup.png" alt="logo lou pélou" class="logolou"></a>
This is not a route call

2019-05-21 14:20 UTC, lescadev commented on templates/base.html.twig
>                  <li><a href="https://www.facebook.com/lechemindupelou/" target="_blank"><img class="fb" src="/Facebookicon.png" alt="fb"></a></li>
No uppercase in filenames

2019-05-21 14:20 UTC, lescadev commented on templates/base.html.twig
> +                <li><a href={{ path('mentionL') }}>Mentions légales</a></li>
No uppercase in routes name

2019-05-21 15:31 UTC, lescadev commented on src/Controller/HomeController.php
> +     * @Route("/", name="index")
No need to rename this route, "home" was good

2019-05-21 15:32 UTC, lescadev approved these changes

2019-05-22 07:08 UTC, Mihidari approved these changes

2019-05-22 08:03 UTC, NicolasROULON approved these changes

2019-05-22 08:04 UTC, merged