Feature/inscription categorie presta
lescadev/loupelou pull request #47
Opened 2019-07-25 08:52 UTC by Anthony8729

2019-07-25 09:53 UTC, Mihidari reviewed
Vous pouvez ajouter le JS pour que la select catégorie ne s'affiche que si la checkbox prestataire est cochée svp

2019-07-26 13:00 UTC, nicolasvauche requested changes
Please solve conflicts first

2019-07-26 14:44 UTC, Toohk approved these changes

2019-07-29 07:49 UTC, nicolasvauche approved these changes

2019-07-29 07:55 UTC, Mihidari approved these changes

2019-07-29 07:56 UTC, merged