Feature/forgotpassword
lescadev/loupelou pull request #81
Opened 2019-08-01 12:34 UTC by Rob1tabard

2019-08-01 12:44 UTC, Mihidari approved these changes

2019-08-01 14:46 UTC, nicolasvauche requested changes
- Please replace "Votre mot de passe a été renouvelé" by "Votre mot de passe a été réinitialisé"
- Please fix typo in mail "Réinitialisation du mots de passe"
- Please fix typo in form "Entrez votre mots de passe"
- Please fix typo in mail object "Objet : Réinitialisation mots de passe"

**IMPORTANT**
- Please catch error if I try to follow the link after password reset (no user loaded >>> access forbidden)

2019-08-01 15:12 UTC, nicolasvauche approved these changes

2019-08-02 09:49 UTC, Toohk approved these changes
Ça marche mais y'a un problème dans les migrations

2019-08-02 10:15 UTC, merged